version: '3.8'

services:
  app:
    build: .
    container_name: nestjs_app
    ports:
      - '3000:3000'
    depends_on:
      - elasticsearch
    environment:
      - NODE_ENV=production
      - ELASTICSEARCH_HOST=elastic
      - ELASTICSEARCH_PORT=9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=EiU5xRTIomIoRe3Z7RIn
      - discovery.type=single-node
    ports:
      - '9200:9200'
      - '9300:9300' 
